### ISSUE TITLE
Inexisting requirments

### ISSUE THREAD

**Issue by DarkRedman** [jminardi/syncnet#4]
Hello, I want to try this program, I did a clone with git. I'm Manjaro distribution (arch based) I try to install packages : python-bitcoinlib atom enaml BTSync
But thoses doesn't exist, so then I try to execute setup.py with the argument build to try it on its own. It says it runned the build setup but it doesn't do anything.

I even try to run setup with install argument but it fails on error :

```
In file included from /usr/include/python3.3m/Python.h:51:0,
                 from enaml/src/pythonhelpers.h:9,
                 from enaml/src/weakmethod.cpp:10:
enaml/src/weakmethod.cpp:229:14: attention : ‘WeakMethod__doc__’ defined but not used [-Wunused-variable]
 PyDoc_STRVAR(WeakMethod__doc__,
              ^
/usr/include/python3.3m/pymacro.h:50:37: note: in definition of macro ‘PyDoc_VAR’
 #define PyDoc_VAR(name) static char name[]
                                     ^
enaml/src/weakmethod.cpp:229:1: note: in expansion of macro ‘PyDoc_STRVAR’
 PyDoc_STRVAR(WeakMethod__doc__,
 ^
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

Can you help to fix it ?

**Comment by arthurbarros** [comment]
Couldn't run it too.
Same problem with the dependencies.

Mac OS X 10.8.5

```
$ python --version
Python 2.7.5
```

Ubuntu 12.04 LTS 64bit

```
$ python --version
Python 2.7.3
```

**Comment by jminardi** [comment]
You need to follow the installation instructions for enaml: http://nucleic.github.io/enaml/docs/get_started/installation.html

Did you successfully install that? You will also need to apply for an API key from bittorrent and pass that information to the bsync executable. You can find more information about that on the python-btsync page: https://github.com/jminardi/python-btsync

**Comment by jminardi** [comment]
closing this as the API key is now built into `python-btsync`
